//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N3XeS.CSharp.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N3XeS.CSharp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be null and empty.
        /// </summary>
        public static string StringValueMustBeNullAndEmpty {
            get {
                return ResourceManager.GetString("StringValueMustBeNullAndEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be null, empty, or white space.
        /// </summary>
        public static string StringValueMustBeNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringValueMustBeNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be empty.
        /// </summary>
        public static string StringValueMustNotBeEmpty {
            get {
                return ResourceManager.GetString("StringValueMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be empty or white space.
        /// </summary>
        public static string StringValueMustNotBeEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringValueMustNotBeEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be the default of T.
        /// </summary>
        public static string ValueMustBeDefault {
            get {
                return ResourceManager.GetString("ValueMustBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be the default minimum Character value.
        /// </summary>
        public static string ValueMustBeDefaultCharacter {
            get {
                return ResourceManager.GetString("ValueMustBeDefaultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be an empty Globally Unique Identifier (Guid).
        /// </summary>
        public static string ValueMustBeEmptyGuid {
            get {
                return ResourceManager.GetString("ValueMustBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be an even number.
        /// </summary>
        public static string ValueMustBeEven {
            get {
                return ResourceManager.GetString("ValueMustBeEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be an even number and not null.
        /// </summary>
        public static string ValueMustBeEvenNotNull {
            get {
                return ResourceManager.GetString("ValueMustBeEvenNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than.
        /// </summary>
        public static string ValueMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to.
        /// </summary>
        public static string ValueMustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than.
        /// </summary>
        public static string ValueMustBeLessThan {
            get {
                return ResourceManager.GetString("ValueMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than or equal to.
        /// </summary>
        public static string ValueMustBeLessThanOrEqual {
            get {
                return ResourceManager.GetString("ValueMustBeLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be the minimum DateTime.
        /// </summary>
        public static string ValueMustBeMinimumDateTime {
            get {
                return ResourceManager.GetString("ValueMustBeMinimumDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be negative.
        /// </summary>
        public static string ValueMustBeNegative {
            get {
                return ResourceManager.GetString("ValueMustBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be null.
        /// </summary>
        public static string ValueMustBeNull {
            get {
                return ResourceManager.GetString("ValueMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be an odd number.
        /// </summary>
        public static string ValueMustBeOdd {
            get {
                return ResourceManager.GetString("ValueMustBeOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be an odd number and not null.
        /// </summary>
        public static string ValueMustBeOddNotNull {
            get {
                return ResourceManager.GetString("ValueMustBeOddNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be positive.
        /// </summary>
        public static string ValueMustBePositive {
            get {
                return ResourceManager.GetString("ValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero.
        /// </summary>
        public static string ValueMustBeZero {
            get {
                return ResourceManager.GetString("ValueMustBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be the default of T.
        /// </summary>
        public static string ValueMustNotBeDefault {
            get {
                return ResourceManager.GetString("ValueMustNotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be the default minimum Character value.
        /// </summary>
        public static string ValueMustNotBeDefaultCharacter {
            get {
                return ResourceManager.GetString("ValueMustNotBeDefaultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be an empty Globally Unique Identifier (Guid).
        /// </summary>
        public static string ValueMustNotBeEmptyGuid {
            get {
                return ResourceManager.GetString("ValueMustNotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be the minimum DateTime.
        /// </summary>
        public static string ValueMustNotBeMinimumDateTime {
            get {
                return ResourceManager.GetString("ValueMustNotBeMinimumDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be null.
        /// </summary>
        public static string ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ValueMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be zero.
        /// </summary>
        public static string ValueMustNotBeZero {
            get {
                return ResourceManager.GetString("ValueMustNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is out of range.
        /// </summary>
        public static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
